version: '2.2'

services:
  powerdns:
    build: powerdns/
    image: mahoul/pdns-sqlite
    ports:
      - "${PDNS_IP}:53:53"
      - "${PDNS_IP}:53:53/udp"
      - "${PDNS_IP}:8081:8081"
    environment:
#      PDNS_api_key: "secret"
#      PDNS_master: "yes"
#      PDNS_api: "yes"
#      PDNS_webserver: "yes"
#      PDNS_webserver_address: "0.0.0.0"
#      PDNS_webserver_allow_from: "0.0.0.0/0"
#      PDNS_webserver_password: "secret"
#      PDNS_version_string: "anonymous"
#      PDNS_default_ttl: "1500"
#      PDNS_soa_minimum_ttl: "1200"
#      PDNS_default_soa_name: "ns1.${DOMAIN}"
#      PDNS_default_soa_mail: "hostmaster.${DOMAIN}"
      PDNS_SQLITE_UID: ${PDNS_SQLITE_UID}
      PDNS_SQLITE_GID: ${PDNS_SQLITE_UID}

    volumes:
      - "${PDNS_DB_DIR}:/db"
    
  powerdns-admin:
    build: powerdns-admin/
    image: mahoul/pdns-admin-sqlite
    ports:
      - "${PDNS_ADMIN_IP}:80:9191"
    environment:
#      PDNS_PROTO: "http"
#      PDNS_API_KEY: "${PDNS_API_KEY}"
#      PDNS_HOST: "powerdns"
#      PDNS_PORT: "8081"
      PDNS_HOST: "${PDNS_IP}"
#      PDNSADMIN_SECRET_KEY: "secret"
#      PDNSADMIN_SQLA_DB_HOST: "mysql"
#      PDNSADMIN_SQLA_DB_PASSWORD: "${DB_USER_PASSWORD}"
#      PDNSADMIN_SQLA_DB_NAME: "${DB_NAME}"
#      PDNSADMIN_SQLA_DB_USER: "${DB_USERNAME}"
    depends_on:
      - powerdns
    links:
      - powerdns
    volumes:
      - "${PDNS_ADMIN_DB_DIR}:/db"

